### ISSUE TITLE
App "EPUB/CBZ/PDF ebook reader" cannot be installed because it is not compatible with this version of the server.

### ISSUE THREAD

**Issue by plvallee** [devnoname120/epubviewer#2]
App "EPUB/CBZ/PDF ebook reader" cannot be installed because it is not compatible with this version of the server.

**Comment by plvallee** [comment]
Hi,
Sorry for the lack of introduction. I just said when I install after updated nextcloud 20.0.1 I have this error when i enabled with the command sudo -u www-data php occ app:enable epubreader-master. If you know what and may you help me. it would very appreciate. Thanks!

**Comment by devnoname120** [comment]
You are using the wrong repo. This repo is `epubviewer` not `epubreader`. App is published here: https://apps.nextcloud.com/apps/epubviewer
